In [2]:
import numpy as np

In [4]:
data = [1,2,3,4,5]  ## calling a list from an array
a1 = np.array(data)
a1

array([1, 2, 3, 4, 5])

In [5]:
data1 = [[1,2,3,4],[5,6,7,8]] ## two dimentional array
a2 = np.array(data1)
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
a2[1,3]  ## 1- 0,0 / 2-0,1....5- 1,0 / 8 - 1,3

8

In [8]:
a2.dtype  ## returning data type of array

dtype('int32')

In [10]:
smallerInteger = np.array(a2 , dtype = np.int8) # specifying the datatype of array
smallerInteger

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [12]:
a1.nbytes # number of bytes required to store data

20

In [13]:
smallerInteger.nbytes

8

In [9]:
a1.ndim    ## returns number of dimentions in the array

1

In [10]:
a2.ndim

2

In [6]:
a4 = np.array([1,2,3,4],ndmin=5)
a4

array([[[[[1, 2, 3, 4]]]]])

In [19]:
np.arange(5)   ## returns integer values from 0 to 4

array([0, 1, 2, 3, 4])

In [20]:
np.linspace(5,10)  ## returns float type values b/w 5 to 10

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [23]:
np.linspace(1,10,5) ## returns only 5 float numbers

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
rand_val = np.random.rand(3)
rand_val

array([0.14489733, 0.63023495, 0.26990631])

In [30]:
rand_val_2d = np.random.rand(2,3)
rand_val_2d

array([[0.96359987, 0.01129709, 0.54839023],
       [0.09808638, 0.56204047, 0.91192106]])

In [29]:
rand_val_2d.ndim

2

In [26]:
rand_int = np.random.randint(0,100,20) ## 20 int values b/w 0 and 100
rand_int

array([26, 14, 21, 78, 58, 64, 11, 79, 80,  4, 70, 97, 35, 43,  5, 90, 27,
       25, 87, 46])

In [33]:
 ## two dimentional array
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape ## returns rows and columns

(2, 4)

In [34]:
a2.shape[0]

2

In [36]:
a2.shape[1]

4

In [18]:
a2.size ## returns total number of elements in an array

8

In [41]:
a = np.arange(2,10,2)  ## last 2 indicates steps in b/w
a

array([2, 4, 6, 8])

In [42]:
new_a = a.reshape(2,2)
new_a

array([[2, 4],
       [6, 8]])

In [17]:
np.reshape(a,[2,2])

array([[2, 4],
       [6, 8]])

In [9]:
a3 = np.arange(0,10)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.reshape(a3,[2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.reshape(a3,[5,2])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
a3[0]

0

In [43]:
a3[3]

3

In [47]:
a2[0,1]

2

In [30]:
a2[1,3]

8

In [31]:
a3[0:3]

array([0, 1, 2])

In [32]:
a3[:4]

array([0, 1, 2, 3])

In [33]:
a3[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a3[1:6:2]

array([1, 3, 5])

In [36]:
a3[::2]

array([0, 2, 4, 6, 8])

In [37]:
a2[1,0:2]

array([5, 6])

In [38]:
a3[-1]

9

In [39]:
a3[-4:-1]

array([6, 7, 8])

In [40]:
a2[:-1]

array([[1, 2, 3, 4]])

In [13]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
a[::-1,::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [44]:
np.flip(a,axis=0)

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [45]:
np.flip(a,axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6]])

In [16]:
a = np.arange(0,5)
b = np.arange(5,10)
a

array([0, 1, 2, 3, 4])

In [50]:
b

array([5, 6, 7, 8, 9])

In [47]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [54]:
np.vstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [55]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
np.concatenate((a,b),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
a

array([[0, 1, 2, 3, 4]])

In [86]:
b

array([[5, 6, 7, 8, 9]])

In [84]:
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a1

array([[1, 2],
       [3, 4]])

In [92]:
a2

array([[5, 6],
       [7, 8]])

In [20]:
a = np.concatenate((a1,a2),axis=1)
a

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [21]:
a = np.concatenate((a1,a2),axis=0)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [95]:
np.append(a1,a2,axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [59]:
a1+5

array([ 6,  7,  8,  9, 10])

In [60]:
a1-5

array([-4, -3, -2, -1,  0])

In [61]:
a1*5

array([ 5, 10, 15, 20, 25])

In [62]:
a1**2

array([ 1,  4,  9, 16, 25])

In [63]:
a = np.arange(5,15,2)

In [64]:
a

array([ 5,  7,  9, 11, 13])

In [65]:
np.mean(a)

9.0

In [67]:
np.median(a)

9.0

In [68]:
np.std(a)

2.8284271247461903

In [69]:
np.var(a)

8.0

In [71]:
np.zeros(5,dtype=np.int32)

array([0, 0, 0, 0, 0])

In [72]:
np.zeros((2,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [73]:
np.ones((2,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
full_array = np.full((2,4),8)
full_array

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [74]:
np.random.rand(2,3)

array([[0.0217302 , 0.42703614, 0.56860899],
       [0.83137475, 0.87696103, 0.58876992]])

In [75]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [76]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [78]:
np.eye(5,dtype=np.int32,k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [79]:
np.eye(5,dtype=np.int32,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [80]:
np.random.randint(50,size=(3,5))

array([[45, 19, 23, 35, 40],
       [40, 12, 47,  5, 46],
       [37, 48, 39,  6, 23]])

In [81]:
np.random.randint(50,size=(5))

array([32, 43, 39,  9, 17])

In [82]:
np.random.randint(4,5)

4

In [88]:
np.random.choice([4,5])

4

In [48]:
arr1 = np.array([1,2,3,5])
arr1

array([1, 2, 3, 5])

In [50]:
new_arr1 = np.insert(arr1,3,4)
new_arr1

array([1, 2, 3, 4, 5])

In [51]:
arr2 = np.append(arr1,6)
arr2

array([1, 2, 3, 5, 6])

In [53]:
del_arr = np.delete(arr2,4)
del_arr

array([1, 2, 3, 5])

In [54]:
arr4 = np.array([5,7,8,2,1])
sort_arr = np.sort(arr4)
sort_arr

array([1, 2, 5, 7, 8])

In [57]:
a= np.arange(1,10).reshape(3,3)
b= np.arange(1,4)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
b

array([1, 2, 3])

In [59]:
a+b  ## broadcasting---> because a and b have different dimention python broadcast b as 3*3 

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])